### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by jack1230** [nasyxx/nautc#2]
I have followed the example that is detailed and it does not work as it shows error when using the convert

**Comment by nasyxx** [comment]
Can you share the details of error?

**Comment by jack1230** [comment]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 13: character maps to <undefined>

https://ibb.co/b172GpG

**Comment by nasyxx** [comment]
It should work if you add

```
, encoding='utf-8'
```

after "rt" in the nautc.py gzip.open line 60.

It's interesting that windows didn't use utf-8 by default.

**Comment by jack1230** [comment]
It works already, thanks
